### ISSUE TITLE
you can teleport inside the vehicle from far distance 

### ISSUE THREAD

**Issue by BlackburnUTG** [ampersand38/ride-where-you-look#10]
if you press toggle show seats button near the vehicle, and run away from it. Seat icons are still shown and you can get inside the vehicle, even if you very far from vehicle
https://www.youtube.com/watch?v=c3ILia7WYbg

**Comment by BlackburnUTG** [comment]
can you remove toggle show seats ability, before this bug will get fixed?

**Comment by ampersand38** [comment]
Thank you =) Closed by https://github.com/ampersand38/ride-where-you-look/commit/48a6f31ff757b4492f6161168c9a28666c3539b2
