### ISSUE TITLE
Some vehicles have proxies showing 2 m above the character position

### ISSUE THREAD

**Issue by ampersand38** [ampersand38/ride-where-you-look#3]

**Comment by kuloodporny** [comment]
A possible solution: an array of 3D offsets for cargo, and offset for gunners and pilots, much like blacklisting the seats.

**Comment by ampersand38** [comment]
Since so many mod vehicles have this issue as well, I think I'll have to move it out of config and into a CBA classEH, to avoid dependencies and compats.

**Comment by sevn10** [comment]
This seems to be an issue with some of the 3cb vehicles as well, like the Jackal & Coyote that I noticed primarily.

**Comment by sevn10** [comment]
You're awesome! All the 3cb vehicles are working great with the latest update other than UK3CB_BAF_Merlin_HC4_18_GPMG_MTP. That Merlin seems to want to keep pushing passengers to seat 1, though looking at gun positions and changing to them works. It's not a big deal though.

**Comment by ampersand38** [comment]
https://github.com/ampersand38/ride-where-you-look/commit/e7c9f58ae7e1d7189f3c3001024806a15fbf7d40 this should fix like 95% of proxies, I think.

**Comment by ampersand38** [comment]
closed by https://github.com/ampersand38/ride-where-you-look/commit/7cf2a1404478abcf7cba541ba3f3b61f546e14eb
