### ISSUE TITLE
Feature suggestion: Display icons of unselected available positions

### ISSUE THREAD

**Issue by kuloodporny** [ampersand38/ride-where-you-look#4]
It would be easier to locate the vehicle's available positions if they were all being drawn, although differently to the currently selected position. For example they could be drawn translucent and without tags.

**Comment by kuloodporny** [comment]
I have noticed that the code has room for performance optimizations (f.e. selectMin in a loop), and occasional unreliabilities such as float comparisons. They may become apparent if the code is expanded as it is.

**Comment by ampersand38** [comment]
How's this look?
https://github.com/ampersand38/ride-where-you-look/commit/e313fb50c76823809bfd138483ac041c9cd7b42c
https://youtu.be/nFvhYsaT0I4

**Comment by kuloodporny** [comment]
Looks great! And from the brief look at the code it's also faster now.
