### ISSUE TITLE
Clipboard abuse

### ISSUE THREAD

**Issue by kuloodporny** [ampersand38/ride-where-you-look#5]
The Steam Workshop version as of now (10th July) keeps overriding the Windows Clipboard.
 Could this behavior please be made optional and disabled by default? I know it's useful for debugging purposes.

**Comment by ampersand38** [comment]
Oops!

https://github.com/ampersand38/ride-where-you-look/commit/beff9252982a4cef11e3141200a92c02f15c4f25
