### ISSUE TITLE
Display type of seat also when not looking at it

### ISSUE THREAD

**Issue by kuloodporny** [ampersand38/ride-where-you-look#7]
Recognizing which icon stands for which position takes time and effort because they all look the same.

Can we please have the inactive icons match the type of seat even when not interacting with it?

**Comment by ampersand38** [comment]
https://github.com/ampersand38/ride-where-you-look/commit/b3086372bf8e60b7218edce4cd139e4ccb9aec89

**Comment by kuloodporny** [comment]
Looks good, although I frown about the usage of switch statement with no early exits, resulting in repeated substring search:
```
                switch (true) do {
                    case ("cargo" in _x): {
```

Ideally the type of the seat should be cached somewhere, perhaps as vehicle variable, so that isEqualTo can be used instead of multiple substring searches.
