### ISSUE TITLE
RHS special turrets issues

### ISSUE THREAD

**Issue by kuloodporny** [ampersand38/ride-where-you-look#8]
The special turrets of RHS content, such as pintle mounted NSV on T-72 tank should not be accessible from outside of vehicle. Frankly I don't know much about the technical side of that one, but that surely is an issue.

**Comment by ampersand38** [comment]
They can likely be blacklisted https://github.com/ampersand38/ride-where-you-look/commit/29176c8693858d06676f2e620be3954d189a3056

**Comment by ampersand38** [comment]
Locked turrets are no longer eligible for selection =)
https://github.com/ampersand38/ride-where-you-look/blob/master/addons/main/functions/fnc_showSeatsPFH.sqf#L71-L73
